/**
 * Copyright 2004-present Facebook. All Rights Reserved.
 *
 * 
 * @providesModule writeFlowFile
 */

'use strict';

// const printFlowTypes = require('printFlowTypes');

function writeFlowFile(outputDirectory, node, platform) {
  //   const moduleName = node.name + '.flow';
  //   const header = `/**
  //  * Copyright 2004-present Facebook. All Rights Reserved.
  //  *
  //  * This file was generated by:
  //  *   js1 build relay
  //  *
  //  * ${'@'}providesModule ${moduleName}
  //  * ${SignedSource.getSigningToken()}
  //  * ${'@'}flow
  //  */

  // 'use strict';

  // `;
  //   const types = printFlowTypes(node);

  //   if (!types) {
  //     throw new Error('No types generated for node: ' + node.name);
  //   }

  //   const fileName = platform ? moduleName + '.' + platform : moduleName;
  //   outputDirectory.writeFile(
  //     fileName + '.js',
  //     SignedSource.signFile(header + types + '\n')
  //   );
}

module.exports = writeFlowFile;